# Generated by Django 3.2.9 on 2021-11-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='department',
            new_name='departments',
        ),
    ]
