# Generated by Django 3.2.9 on 2021-11-26 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
