# Generated by Django 3.2.9 on 2021-11-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rename_department_client_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='departments',
        ),
        migrations.CreateModel(
            name='ClientToDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='entities.department')),
            ],
        ),
    ]
