# Generated by Django 3.2.9 on 2021-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_client_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='identification_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
