# Generated by Django 3.2.9 on 2021-11-28 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20211128_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttodepartment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
