# Generated by Django 3.2.9 on 2021-11-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_clienttodepartment_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttodepartment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clienttodepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='entities.department'),
        ),
    ]
